version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GOOGLE_API_KEY
      - REDIS_PORT
      - REDIS_HOST
    ports:
      - "5000:5000"
    depends_on:
      - redis
    volumes:
      - .:/app
  redis:
    image: redis:5